//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterClass
    {
        public Nullable<int> student_id { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<bool> isPaid { get; set; }
        public int registerclasses { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Student Student { get; set; }
    }
}
