//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.RegisterClasses = new HashSet<RegisterClass>();
        }
    
        public int StudentId { get; set; }
        public string IdUser { get; set; }
        public Nullable<int> IdMajor { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string PhoneNum { get; set; }
        public string StudentImg { get; set; }
        public Nullable<double> SchoolAvg { get; set; }
        public string CertificateImg { get; set; }
        public string PersonalIDImg { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Major Major { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterClass> RegisterClasses { get; set; }
    }
}
